/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 476115ab656df0b97b8d92b01048d55d)
interface __BaseEnv_Env {
	FEEDBACK_BUCKET: R2Bucket;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
